added flake8 for linting

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,5 +1,12 @@
 #!/bin/sh
 
+echo "Running lint..."
+make lint
+if [ $? -ne 0 ]; then
+  echo "Format failed, aborting commit."
+  exit 1
+fi
+
 echo "Running format..."
 make format
 if [ $? -ne 0 ]; then
